export type ResponseType = 'yesno' | 'text' | 'number' | 'select' | 'multiselect' | 'ynlist';

export type Question = {
  id: string;
  text: string;
  subject: string; // Technical / Commercial / Scope & Departmental Involvement / etc.
  responseType: ResponseType;
  options?: Array<{ value: string; label: string }>; // For yesno, select, multiselect
  placeholder?: string; // For text and number inputs
  validation?: {
    required?: boolean;
    min?: number;
    max?: number;
    pattern?: string;
  };
};

export const questionsData: Question[] = [
  {
    id: "q1",
    text: "Would you like us to submit a proposal that includes an eInvoicing solution as an ASP or are you seeking only advisory services related to selecting an ASP, along with guidance during implementation and post-implementation support with the chosen ASP?",
    subject: "Commercial",
    responseType: 'select',
    options: [
      { value: "asp_proposal", label: "ASP solution proposal" },
      { value: "advisory_only", label: "Advisory services only" },
      { value: "both", label: "Both" },
    ],
  },
  {
    id: "q2",
    text: "Can you please share a high-level diagram of Strata's technology ecosystem? This should provide us with more information on the integration requirements with your existing system landscape.",
    subject: "Technical",
    responseType: 'text',
    placeholder: "Please provide a description or upload details",
  },
  {
    id: "q3",
    text: "Could you please specify the number of business entities you operate?",
    subject: "Technical",
    responseType: 'number',
    placeholder: "Enter number",
    validation: { required: true, min: 1 },
  },
  {
    id: "q4",
    text: "Could you please specify how many revenue streams are there per entity?",
    subject: "Technical",
    responseType: 'number',
    placeholder: "Enter number",
    validation: { required: true, min: 1 },
  },
  {
    id: "q5",
    text: "Could you please specify how many systems are there per entity?",
    subject: "Technical",
    responseType: 'number',
    placeholder: "Enter number",
    validation: { required: true, min: 1 },
  },
  {
    id: "q5a",
    text: "Please provide the number of supply transactions per annum (sales invoices, credit notes) for B2B and B2G",
    subject: "Commercial",
    responseType: 'number',
    placeholder: "Enter number",
    validation: { required: true, min: 0 },
  },
  {
    id: "q5b",
    text: "Please provide the number of supply transactions per annum (sales invoices, credit notes) for B2C",
    subject: "Commercial",
    responseType: 'number',
    placeholder: "Enter number",
    validation: { required: true, min: 0 },
  },
  {
    id: "q6",
    text: "Please provide the estimated number of all purchase transactions per annum (purchase invoices, credit notes)",
    subject: "Commercial",
    responseType: 'number',
    placeholder: "Enter number",
    validation: { required: true, min: 0 },
  },
  {
    id: "q7",
    text: "Are templates of all sales invoices and credit notes the same?",
    subject: "Technical",
    responseType: 'yesno',
    options: [
      { value: "1", label: "Yes" },
      { value: "0", label: "No" },
    ],
  },
  {
    id: "q7a",
    text: "If not, please provide number of different templates each for invoices and credit notes",
    subject: "Technical",
    responseType: 'text',
    placeholder: "Please specify",
  },
  {
    id: "q8",
    text: "Do you have inhouse IT capability or an IT vendor to extract data from your systems and provide in a standard template?",
    subject: "Technical",
    responseType: 'select',
    options: [
      { value: "inhouse", label: "Inhouse IT capability" },
      { value: "vendor", label: "IT vendor" },
      { value: "both", label: "Both" },
      { value: "none", label: "None" },
    ],
  },
  {
    id: "q9",
    text: "Do your systems have the capability to integrate with other systems using API or SFTP (please specify)?",
    subject: "Technical",
    responseType: 'select',
    options: [
      { value: "api", label: "API" },
      { value: "sftp", label: "SFTP" },
      { value: "both", label: "Both API and SFTP" },
      { value: "none", label: "None" },
    ],
  },
  {
    id: "q10",
    text: "Number of entities in UAE, including branches",
    subject: "Technical",
    responseType: 'number',
    placeholder: "Enter number",
    validation: { required: true, min: 1 },
  },
  {
    id: "q11",
    text: "Name of ERPs and its make/model/version (Please list if there are multiple)",
    subject: "Technical",
    responseType: 'text',
    placeholder: "e.g., SAP ECC 6.0, Oracle EBS 12.2, etc.",
  },
  {
    id: "q12",
    text: "Annual number of B2B invoices",
    subject: "Technical",
    responseType: 'number',
    placeholder: "Enter number",
    validation: { required: true, min: 0 },
  },
  {
    id: "q13",
    text: "Annual number of B2G invoices",
    subject: "Technical",
    responseType: 'number',
    placeholder: "Enter number",
    validation: { required: true, min: 0 },
  },
  {
    id: "q14",
    text: "Annual number of B2C invoices",
    subject: "Technical",
    responseType: 'number',
    placeholder: "Enter number",
    validation: { required: true, min: 0 },
  },
  {
    id: "q15",
    text: "Average number of line items in a single sales invoice",
    subject: "Technical",
    responseType: 'number',
    placeholder: "Enter number",
    validation: { required: true, min: 1 },
  },
  {
    id: "q16",
    text: "Average number of line items in a single purchase invoice",
    subject: "Technical",
    responseType: 'number',
    placeholder: "Enter number",
    validation: { required: true, min: 1 },
  },
  {
    id: "q17",
    text: "Annual number of purchase invoices from overseas suppliers",
    subject: "Technical",
    responseType: 'number',
    placeholder: "Enter number",
    validation: { required: true, min: 0 },
  },
  {
    id: "q18",
    text: "Annual number of local purchase transactions",
    subject: "Technical",
    responseType: 'number',
    placeholder: "Enter number",
    validation: { required: true, min: 0 },
  },
  {
    id: "q19",
    text: "Whether e-invoice PDF copy must be generated using XXX e-invoice SaaS solution or through ERP.",
    subject: "Technical",
    responseType: 'select',
    options: [
      { value: "saas", label: "XXX e-invoice SaaS solution" },
      { value: "erp", label: "Through ERP" },
      { value: "both", label: "Both" },
    ],
  },
  {
    id: "q20",
    text: "Preferable integration model",
    subject: "Technical",
    responseType: 'select',
    options: [
      { value: "api", label: "API" },
      { value: "sftp", label: "SFTP" },
      { value: "manual_excel", label: "Manual via MS Excel upload" },
    ],
  },
  {
    id: "q21",
    text: "Refer 4. Scope of Services : 8. Provide guidance on data migration, security, and interoperability with existing systems.",
    subject: "Technical",
    responseType: 'text',
    placeholder: "Please provide details",
  },
  {
    id: "q22",
    text: "Please confirm data migration from which systems, share name and version details, what guidance on security is expected",
    subject: "Technical",
    responseType: 'text',
    placeholder: "Please provide system names, versions, and security requirements",
  },
  {
    id: "q23",
    text: "Changes within ERP with respect to e-invoice",
    subject: "Technical",
    responseType: 'text',
    placeholder: "Please describe expected changes",
  },
  {
    id: "q24",
    text: "Will be managed by Strata or XXX is expected to do the integration from ERP to XXX e-invoice solution.",
    subject: "Technical",
    responseType: 'select',
    options: [
      { value: "strata", label: "Managed by Strata" },
      { value: "xxx", label: "XXX to do integration" },
      { value: "both", label: "Both" },
    ],
  },
  {
    id: "q25",
    text: "Refer 4. Scope of Services : 11. Assist in preparing compliance documentation and responding to Ministry audits, if required.",
    subject: "Technical",
    responseType: 'text',
    placeholder: "Please provide details",
  },
  {
    id: "q26",
    text: "Could you please confirm that this scope is intended solely to guide Strata through the first VAT return filing post go-live, which may involve changes to the filing process and approach? Just to clarify, this does not include any VAT audit assistance, correct?",
    subject: "Technical",
    responseType: 'yesno',
    options: [
      { value: "1", label: "Yes" },
      { value: "0", label: "No" },
    ],
  },
  {
    id: "q27",
    text: "Refer 4 . 10. Provide post-implementation monitoring and assistance.",
    subject: "Technical",
    responseType: 'text',
    placeholder: "Please provide details",
  },
  {
    id: "q28",
    text: "Post implementation we have support helpdesk to help users on any queries related to e-invoice application, Could you share what is the expectation for monitoring and assistance.",
    subject: "Technical",
    responseType: 'text',
    placeholder: "Please describe expectations",
  },
  {
    id: "q29",
    text: "Will the respective departments representatives available for discovery workshops?",
    subject: "Scope & Departmental Involvement",
    responseType: 'yesno',
    options: [
      { value: "1", label: "Yes" },
      { value: "0", label: "No" },
    ],
  },
  {
    id: "q30",
    text: "Are international branches or affiliates (if any) included in scope, or is this limited to UAE operations?",
    subject: "Scope & Departmental Involvement",
    responseType: 'select',
    options: [
      { value: "uae_only", label: "UAE operations only" },
      { value: "international_included", label: "International branches/affiliates included" },
    ],
  },
  {
    id: "q31",
    text: "Will internal systems across all departments (e.g., HR, SCM, Finance etc) be accessible for integration and assessment?",
    subject: "Scope & Departmental Involvement",
    responseType: 'yesno',
    options: [
      { value: "1", label: "Yes" },
      { value: "0", label: "No" },
    ],
  },
  {
    id: "q32",
    text: "Will current documentation (SOPs, architecture diagrams, BRDs, VAT matrix, invoice formats, etc.) be made available prior to the workshops?",
    subject: "Documentation & Access",
    responseType: 'yesno',
    options: [
      { value: "1", label: "Yes" },
      { value: "0", label: "No" },
    ],
  },
  {
    id: "q33",
    text: "Is there a central document repository or stakeholder who will manage document control and approvals?",
    subject: "Documentation & Access",
    responseType: 'yesno',
    options: [
      { value: "1", label: "Yes" },
      { value: "0", label: "No" },
    ],
  },
  {
    id: "q34",
    text: "What are the core ERP and invoicing systems currently in use (e.g., Oracle, SAP, Dynamics)?",
    subject: "Systems Landscape",
    responseType: 'text',
    placeholder: "Please list all systems",
  },
  {
    id: "q35",
    text: "Do you currently use any middleware, ETL, or data integration tools (e.g., MuleSoft, Informatica)?",
    subject: "Systems Landscape",
    responseType: 'text',
    placeholder: "Please list tools or enter 'None'",
  },
  {
    id: "q36",
    text: "Are any cloud-based or third-party systems in scope for invoicing or data exchange?",
    subject: "Systems Landscape",
    responseType: 'yesno',
    options: [
      { value: "1", label: "Yes" },
      { value: "0", label: "No" },
    ],
  },
  {
    id: "q37",
    text: "What is the average monthly invoice volume (incoming and outgoing)?",
    subject: "Invoice Volume & Complexity",
    responseType: 'number',
    placeholder: "Enter number",
    validation: { required: true, min: 0 },
  },
  {
    id: "q38",
    text: "How many invoice types and formats are currently supported (B2B, B2G, credit/debit notes)?",
    subject: "Invoice Volume & Complexity",
    responseType: 'number',
    placeholder: "Enter number",
    validation: { required: true, min: 1 },
  },
  {
    id: "q39",
    text: "Can you share your current understanding of the applicable e-invoicing phase (Phase 1 or 2) from FTA's perspective?",
    subject: "FTA/Compliance Specifics",
    responseType: 'select',
    options: [
      { value: "phase1", label: "Phase 1" },
      { value: "phase2", label: "Phase 2" },
      { value: "unsure", label: "Unsure" },
    ],
  },
  {
    id: "q40",
    text: "Have any formal clarifications from the FTA or MOF already been received by Strata regarding your specific VAT scenarios (e.g., reinsurance, claims)?",
    subject: "FTA/Compliance Specifics",
    responseType: 'yesno',
    options: [
      { value: "1", label: "Yes" },
      { value: "0", label: "No" },
    ],
  },
  {
    id: "q41",
    text: "Is there a preferred ASP already shortlisted or under consideration?",
    subject: "ASP Provider Expectations",
    responseType: 'yesno',
    options: [
      { value: "1", label: "Yes" },
      { value: "0", label: "No" },
    ],
  },
  {
    id: "q42",
    text: "Do you expect the vendor to recommend and implement the ASP, or only assess and suggest?",
    subject: "ASP Provider Expectations",
    responseType: 'select',
    options: [
      { value: "recommend_implement", label: "Recommend and implement" },
      { value: "assess_suggest", label: "Only assess and suggest" },
    ],
  },
  {
    id: "q43",
    text: "Are there any existing APIs or integration standards already followed across Strata systems?",
    subject: "Integration Requirements",
    responseType: 'yesno',
    options: [
      { value: "1", label: "Yes" },
      { value: "0", label: "No" },
    ],
  },
  {
    id: "q44",
    text: "Will the ASP be expected to integrate with internal systems in real-time, or is a batch-based model acceptable?",
    subject: "Integration Requirements",
    responseType: 'select',
    options: [
      { value: "realtime", label: "Real-time integration" },
      { value: "batch", label: "Batch-based model" },
      { value: "both", label: "Both" },
    ],
  },
  {
    id: "q45",
    text: "Will Strata provide internal resources for UAT, validations, and sign-offs?",
    subject: "Project Execution",
    responseType: 'yesno',
    options: [
      { value: "1", label: "Yes" },
      { value: "0", label: "No" },
    ],
  },
  {
    id: "q46",
    text: "Do you expect the selected partner to conduct all data mapping manually, or will internal teams assist?",
    subject: "Project Execution",
    responseType: 'select',
    options: [
      { value: "partner_only", label: "Partner conducts all data mapping" },
      { value: "internal_assist", label: "Internal teams will assist" },
      { value: "both", label: "Both" },
    ],
  },
  {
    id: "q47",
    text: "What is the preferred delivery model – on-site, remote, or hybrid?",
    subject: "Project Execution",
    responseType: 'select',
    options: [
      { value: "onsite", label: "On-site" },
      { value: "remote", label: "Remote" },
      { value: "hybrid", label: "Hybrid" },
    ],
  },
  {
    id: "q48",
    text: "What is the process for managing regulatory change impacts after project commencement?",
    subject: "Legal & Change Management",
    responseType: 'text',
    placeholder: "Please describe the process",
  },
  {
    id: "q49",
    text: "Will there be a central point of contact or steering committee for change management?",
    subject: "Legal & Change Management",
    responseType: 'yesno',
    options: [
      { value: "1", label: "Yes" },
      { value: "0", label: "No" },
    ],
  },
  {
    id: "q50",
    text: "How will the implementation phase be handled post-discovery – through a new RFP or extension?",
    subject: "Commercial & Evaluation",
    responseType: 'select',
    options: [
      { value: "new_rfp", label: "New RFP" },
      { value: "extension", label: "Extension" },
      { value: "unsure", label: "Unsure" },
    ],
  },
  {
    id: "q51",
    text: "Can you confirm the list of all internal departments that generate or receive invoices (e.g., Finance, Procurement)?",
    subject: "Business & Functional Scope",
    responseType: 'text',
    placeholder: "Please list all departments",
  },
  {
    id: "q52",
    text: "What are the current types of invoices used internally? (e.g., standard invoices, credit/debit notes, advance invoices)",
    subject: "Business & Functional Scope",
    responseType: 'text',
    placeholder: "Please list all invoice types",
  },
  {
    id: "q53",
    text: "Are there any non-standard or ad-hoc invoicing scenarios (e.g., foreign income, claim reimbursements)?",
    subject: "Business & Functional Scope",
    responseType: 'yesno',
    options: [
      { value: "1", label: "Yes" },
      { value: "0", label: "No" },
    ],
  },
  {
    id: "q54",
    text: "What volume of invoices is processed monthly per department or invoice type?",
    subject: "Business & Functional Scope",
    responseType: 'text',
    placeholder: "Please provide breakdown",
  },
  {
    id: "q55",
    text: "Have there been any clarifications from the FTA on handling foreign investment income, multi-currency invoices, or claim settlements?",
    subject: "Regulatory & Compliance",
    responseType: 'yesno',
    options: [
      { value: "1", label: "Yes" },
      { value: "0", label: "No" },
    ],
  },
  {
    id: "q56",
    text: "Are there any exemptions or special rules currently being applied for any business units or transaction types?",
    subject: "Regulatory & Compliance",
    responseType: 'yesno',
    options: [
      { value: "1", label: "Yes" },
      { value: "0", label: "No" },
    ],
  },
  {
    id: "q57",
    text: "Has Strata already mapped its existing invoice formats against the FTA-mandated formats?",
    subject: "Regulatory & Compliance",
    responseType: 'yesno',
    options: [
      { value: "1", label: "Yes" },
      { value: "0", label: "No" },
    ],
  },
  {
    id: "q58",
    text: "Please provide a list of all source systems involved in invoicing (ERP, CRM, legacy platforms).",
    subject: "Technology & Integration",
    responseType: 'text',
    placeholder: "Please list all systems",
  },
  {
    id: "q59",
    text: "Are these systems cloud-based or on-premises? Are APIs currently available for integration?",
    subject: "Technology & Integration",
    responseType: 'text',
    placeholder: "Please specify for each system",
  },
  {
    id: "q60",
    text: "Is there an enterprise data warehouse or centralized database that can be leveraged for invoice data extraction and mapping?",
    subject: "Technology & Integration",
    responseType: 'yesno',
    options: [
      { value: "1", label: "Yes" },
      { value: "0", label: "No" },
    ],
  },
  {
    id: "q61",
    text: "Are there any existing workflows or BPM tools (e.g., ServiceNow, Appian) involved in approvals or validation of invoices?",
    subject: "Process & Data Flows",
    responseType: 'yesno',
    options: [
      { value: "1", label: "Yes" },
      { value: "0", label: "No" },
    ],
  },
  {
    id: "q62",
    text: "Can you share existing SOPs and workflows for VAT-related processes and reconciliations?",
    subject: "Process & Data Flows",
    responseType: 'yesno',
    options: [
      { value: "1", label: "Yes" },
      { value: "0", label: "No" },
    ],
  },
  {
    id: "q63",
    text: "What are the known challenges in the current invoicing process (e.g., data mismatches, delays, manual work)?",
    subject: "Process & Data Flows",
    responseType: 'text',
    placeholder: "Please describe challenges",
  },
  {
    id: "q64",
    text: "Are you expecting any system upgrades or parallel projects that might impact this implementation timeline?",
    subject: "Customization & Enhancements",
    responseType: 'yesno',
    options: [
      { value: "1", label: "Yes" },
      { value: "0", label: "No" },
    ],
  },
  {
    id: "q65",
    text: "Will changes be required to existing invoice templates or PDF generators used in ERP/CRM?",
    subject: "Customization & Enhancements",
    responseType: 'yesno',
    options: [
      { value: "1", label: "Yes" },
      { value: "0", label: "No" },
    ],
  },
  {
    id: "q66",
    text: "What user interface changes, if any, are expected post e-invoicing go-live (e.g., dashboards, reports)?",
    subject: "Customization & Enhancements",
    responseType: 'text',
    placeholder: "Please describe expected changes",
  },
  {
    id: "q67",
    text: "Does Strata have any preferred ASP vendors or are you open to evaluation and recommendation?",
    subject: "ASP Integration Expectations",
    responseType: 'select',
    options: [
      { value: "preferred", label: "Have preferred vendors" },
      { value: "open", label: "Open to evaluation and recommendation" },
    ],
  },
  {
    id: "q68",
    text: "Are you looking for real-time integration or batch uploads to the ASP portal?",
    subject: "ASP Integration Expectations",
    responseType: 'select',
    options: [
      { value: "realtime", label: "Real-time integration" },
      { value: "batch", label: "Batch uploads" },
      { value: "both", label: "Both" },
    ],
  },
  {
    id: "q69",
    text: "How many business users will be affected by the new e-invoicing process?",
    subject: "People & Training",
    responseType: 'number',
    placeholder: "Enter number",
    validation: { required: true, min: 1 },
  },
  {
    id: "q70",
    text: "Are there any designated internal champions or super users for each department to help with implementation and adoption?",
    subject: "People & Training",
    responseType: 'yesno',
    options: [
      { value: "1", label: "Yes" },
      { value: "0", label: "No" },
    ],
  },
  {
    id: "q71",
    text: "Are there existing training materials for invoicing that need to be updated?",
    subject: "People & Training",
    responseType: 'yesno',
    options: [
      { value: "1", label: "Yes" },
      { value: "0", label: "No" },
    ],
  },
  {
    id: "q72",
    text: "Is there a regulatory deadline by which Strata must be live with B2B e-invoicing?",
    subject: "Timeline & Planning",
    responseType: 'yesno',
    options: [
      { value: "1", label: "Yes" },
      { value: "0", label: "No" },
    ],
  },
  {
    id: "q73",
    text: "Will there be a phased rollout by department, invoice type, or business unit?",
    subject: "Timeline & Planning",
    responseType: 'yesno',
    options: [
      { value: "1", label: "Yes" },
      { value: "0", label: "No" },
    ],
  },
  {
    id: "q74",
    text: "Are there any blackout periods (e.g., financial close, audit windows) during which changes should be avoided?",
    subject: "Timeline & Planning",
    responseType: 'yesno',
    options: [
      { value: "1", label: "Yes" },
      { value: "0", label: "No" },
    ],
  },
  {
    id: "q75",
    text: "Is the discovery phase expected to include a proof-of-concept or just documentation (BRD, TRD, roadmap)?",
    subject: "Commercial & Scope Clarifications",
    responseType: 'select',
    options: [
      { value: "poc", label: "Proof-of-concept" },
      { value: "documentation", label: "Documentation only (BRD, TRD, roadmap)" },
      { value: "both", label: "Both" },
    ],
  },
  {
    id: "q76",
    text: "Will Strata handle legal/regulatory correspondence with FTA, or is vendor support required?",
    subject: "Commercial & Scope Clarifications",
    responseType: 'select',
    options: [
      { value: "strata", label: "Strata will handle" },
      { value: "vendor", label: "Vendor support required" },
      { value: "both", label: "Both" },
    ],
  },
  {
    id: "q77",
    text: "Is support post-discovery phase in-scope (e.g., during FTA integration testing or UAT)?",
    subject: "Commercial & Scope Clarifications",
    responseType: 'yesno',
    options: [
      { value: "1", label: "Yes" },
      { value: "0", label: "No" },
    ],
  },
  {
    id: "q78",
    text: "Please confirm the number of entities in scope",
    subject: "Technical",
    responseType: 'number',
    placeholder: "Enter number",
    validation: { required: true, min: 1 },
  },
  {
    id: "q79",
    text: "Please provide the name of the entities in scope and their business activity",
    subject: "Technical",
    responseType: 'text',
    placeholder: "Please list entities and their activities",
  },
  {
    id: "q80",
    text: "Are the above entities in a VAT group",
    subject: "Technical",
    responseType: 'yesno',
    options: [
      { value: "1", label: "Yes" },
      { value: "0", label: "No" },
    ],
  },
  {
    id: "q81",
    text: "Do you have any current expectations on the timeline for this engagement?",
    subject: "Technical",
    responseType: 'text',
    placeholder: "Please provide timeline expectations",
  },
  {
    id: "q82",
    text: "Where is current invoicing taking place? Is it in the billing systems/ operational systems? Please provide the full details of the system along with the version.",
    subject: "Technical",
    responseType: 'text',
    placeholder: "Please provide system details and versions",
  },
  {
    id: "q83",
    text: "Are there any manual steps in the current invoicing process that could be automated?",
    subject: "Technical",
    responseType: 'yesno',
    options: [
      { value: "1", label: "Yes" },
      { value: "0", label: "No" },
    ],
  },
  {
    id: "q84",
    text: "Please provide information on whether you maintain a list of tax codes for revenue transactions. Alternatively, is the consultant expected to review, prepare, or update this list that may have been developed during the VAT implementation phase?",
    subject: "Technical",
    responseType: 'text',
    placeholder: "Please provide details",
  },
  {
    id: "q85",
    text: "Are Accounts Receivable (AR) and Accounts Payable (AP) managed separately or within the same system?",
    subject: "Technical",
    responseType: 'select',
    options: [
      { value: "separate", label: "Separately" },
      { value: "same", label: "Same system" },
    ],
  },
  {
    id: "q86",
    text: "Does your system use any kind of middleware platform for the data security purpose while pushing the data out of the ERP, Like CPI or PI/PO for SAP, OIC for Oracle?",
    subject: "Technical",
    responseType: 'yesno',
    options: [
      { value: "1", label: "Yes" },
      { value: "0", label: "No" },
    ],
  },
  {
    id: "q87",
    text: "Current system is on Premise or on cloud(Public or Private)?",
    subject: "Technical",
    responseType: 'select',
    options: [
      { value: "onpremise", label: "On Premise" },
      { value: "public_cloud", label: "Public Cloud" },
      { value: "private_cloud", label: "Private Cloud" },
      { value: "hybrid", label: "Hybrid" },
    ],
  },
  {
    id: "q88",
    text: "Is there an ongoing migration of the current invoicing system.",
    subject: "Technical",
    responseType: 'yesno',
    options: [
      { value: "1", label: "Yes" },
      { value: "0", label: "No" },
    ],
  },
  {
    id: "q89",
    text: "Are you planning to migrate, upgrade, or enhance your ERP system in the future? If so, what is the expected timeline for the migration?",
    subject: "Technical",
    responseType: 'text',
    placeholder: "Please provide details and timeline",
  },
  {
    id: "q90",
    text: "Are there any ongoing custom projects that could impact the invoicing process in the future?",
    subject: "Technical",
    responseType: 'yesno',
    options: [
      { value: "1", label: "Yes" },
      { value: "0", label: "No" },
    ],
  },
  {
    id: "q91",
    text: "What is the retention period of the data stored?",
    subject: "Technical",
    responseType: 'text',
    placeholder: "Please specify retention period",
  },
  {
    id: "q92",
    text: "For each of the legal entities, list out the systems used",
    subject: "Technical",
    responseType: 'text',
    placeholder: "Please list systems per entity",
  },
  {
    id: "q93",
    text: "List out the applicable Invoice Types (Y/N): Standard Tax Invoice, Standard Credit Note, Simplified Tax Invoice, Simplified Credit Note, Self-Billing - Invoice, Self-Billing - Credit Note, Commercial Invoice, Commercial credit Note",
    subject: "Technical",
    responseType: 'ynlist',
    options: [
      { value: "standard_tax_invoice", label: "Standard Tax Invoice" },
      { value: "standard_credit_note", label: "Standard Credit Note" },
      { value: "simplified_tax_invoice", label: "Simplified Tax Invoice" },
      { value: "simplified_credit_note", label: "Simplified Credit Note" },
      { value: "self_billing_invoice", label: "Self-Billing - Invoice" },
      { value: "self_billing_credit_note", label: "Self-Billing - Credit Note" },
      { value: "commercial_invoice", label: "Commercial Invoice" },
      { value: "commercial_credit_note", label: "Commercial credit Note" },
    ],
  },
  {
    id: "q94",
    text: "Do you issue Reverse Charge Mechanism (RCM) invoices?",
    subject: "Technical",
    responseType: 'yesno',
    options: [
      { value: "1", label: "Yes" },
      { value: "0", label: "No" },
    ],
  },
  {
    id: "q95",
    text: "Do you have process flow diagrams for Sales invoice cycle?",
    subject: "Technical",
    responseType: 'yesno',
    options: [
      { value: "1", label: "Yes" },
      { value: "0", label: "No" },
    ],
  },
  {
    id: "q96",
    text: "Do you have process flow diagrams for purchase invoice cycle?",
    subject: "Technical",
    responseType: 'yesno',
    options: [
      { value: "1", label: "Yes" },
      { value: "0", label: "No" },
    ],
  },
  {
    id: "q97",
    text: "Also, provide the number of unique transactions - standard taxable supply, export, zero rated, exempt, out of scope, reverse charge etc.",
    subject: "Technical",
    responseType: 'text',
    placeholder: "Please provide breakdown by transaction type",
  },
  {
    id: "q98",
    text: "Please specify the name and version of the ERP and IT system used for managing sales and purchase transactions.",
    subject: "Technical",
    responseType: 'text',
    placeholder: "Please provide system names and versions",
  },
  {
    id: "q99",
    text: "Please list the different billing and operational systems integrated with your ERP, including their modules.",
    subject: "Technical",
    responseType: 'text',
    placeholder: "Please list all systems and modules",
  },
  {
    id: "q100",
    text: "Are there any custom billing or operational systems in use for invoicing processes?",
    subject: "Technical",
    responseType: 'yesno',
    options: [
      { value: "1", label: "Yes" },
      { value: "0", label: "No" },
    ],
  },
  {
    id: "q101",
    text: "Do you already use middleware/integration tools (e.g., MuleSoft, SAP PI, Boomi)?",
    subject: "Technical",
    responseType: 'text',
    placeholder: "Please list tools or enter 'None'",
  },
  {
    id: "q102",
    text: "How many existing APIs are in use to support the invoicing process?",
    subject: "Technical",
    responseType: 'number',
    placeholder: "Enter number",
    validation: { required: true, min: 0 },
  },
  {
    id: "q103",
    text: "Are there any planned upgrades or migrations for the ERP or billing systems in the next 12–18 months?",
    subject: "Technical",
    responseType: 'yesno',
    options: [
      { value: "1", label: "Yes" },
      { value: "0", label: "No" },
    ],
  },
  {
    id: "q104",
    text: "One of the deliverables refers to the Technical Advisory Document. Please clarify the specific outcomes expected in this documentation i.e. integration flows, etc.",
    subject: "Technical",
    responseType: 'text',
    placeholder: "Please specify expected outcomes",
  },
  {
    id: "q105",
    text: "Where is current invoicing taking place (ERP, billing systems, operational systems)?",
    subject: "Technical",
    responseType: 'text',
    placeholder: "Please specify",
  },
  {
    id: "q106",
    text: "Do you have existing system documents (Functional Specifications, TDD, etc.) for all in-scope systems?",
    subject: "Technical",
    responseType: 'yesno',
    options: [
      { value: "1", label: "Yes" },
      { value: "0", label: "No" },
    ],
  },
  {
    id: "q107",
    text: "Do you have a data dictionary for the existing data architecture for all systems under your ERP landscape? When was this last updated?",
    subject: "Technical",
    responseType: 'text',
    placeholder: "Please provide details and last update date",
  },
  {
    id: "q108",
    text: "Do you have documented business processes or process maps for invoicing? If yes, are these up to date?",
    subject: "Technical",
    responseType: 'text',
    placeholder: "Please provide details",
  },
  {
    id: "q109",
    text: "We would recommend developing any training material only once an ASP has come onboard as this will be highly dependent on the workflows available? If there are any other specific training requests this relates to, please let us know.",
    subject: "Technical",
    responseType: 'text',
    placeholder: "Please specify training requirements",
  },
  {
    id: "q110",
    text: "Please provide more context on the type of monitoring and assistance required post implementation as per the deliverable mentioned 'Post Implementation Support Plan'. Does this relate to potential hyper care services available or something different?",
    subject: "Technical",
    responseType: 'text',
    placeholder: "Please describe expectations",
  },
  {
    id: "q111",
    text: "Name of Companies (list all if you are a Group)",
    subject: "Technical",
    responseType: 'text',
    placeholder: "Please list all companies",
  },
  {
    id: "q112",
    text: "Company VAT TRN",
    subject: "Technical",
    responseType: 'text',
    placeholder: "Enter VAT TRN",
  },
  {
    id: "q113",
    text: "Is any of these entities part of the Pilot Program by FTA or decided for Voluntary Adoption by July 2026?",
    subject: "Technical",
    responseType: 'yesno',
    options: [
      { value: "1", label: "Yes" },
      { value: "0", label: "No" },
    ],
  },
  {
    id: "q114",
    text: "How many entities fall under the following phases? Phase 1 companies with revenue of 50M AED or more than. Phase 2 for companies with revenue less than 50M AED.",
    subject: "Technical",
    responseType: 'text',
    placeholder: "Please provide breakdown by phase",
  },
  {
    id: "q115",
    text: "Approx count of sales invoices per annum (B2B and B2G only) from all entities",
    subject: "Technical",
    responseType: 'number',
    placeholder: "Enter number",
    validation: { required: true, min: 0 },
  },
  {
    id: "q116",
    text: "Approx count of purchase invoices per annum for all entities (excluding imports)",
    subject: "Technical",
    responseType: 'number',
    placeholder: "Enter number",
    validation: { required: true, min: 0 },
  },
  {
    id: "q117",
    text: "List of ERPs/Solutions that are used for invoicing",
    subject: "Technical",
    responseType: 'text',
    placeholder: "Please list all ERPs/solutions",
  },
  {
    id: "q118",
    text: "Can ERP Support REST API-Based Integration?",
    subject: "Technical",
    responseType: 'yesno',
    options: [
      { value: "1", label: "Yes" },
      { value: "0", label: "No" },
    ],
  },
  {
    id: "q119",
    text: "Does the ERP System Have 100% Internet Connectivity?",
    subject: "Technical",
    responseType: 'yesno',
    options: [
      { value: "1", label: "Yes" },
      { value: "0", label: "No" },
    ],
  },
  {
    id: "q120",
    text: "Method Used to Share Invoice Copies with Customers",
    subject: "Technical",
    responseType: 'select',
    options: [
      { value: "email", label: "Email" },
      { value: "portal", label: "Customer Portal" },
      { value: "api", label: "API" },
      { value: "other", label: "Other" },
    ],
  },
  {
    id: "q121",
    text: "What is the current invoicing process: (Manual/Automated)",
    subject: "Technical",
    responseType: 'select',
    options: [
      { value: "manual", label: "Manual" },
      { value: "automated", label: "Automated" },
      { value: "hybrid", label: "Hybrid (Both)" },
    ],
  },
  {
    id: "q122",
    text: "How are the invoices shared with the customer and received from the suppliers?",
    subject: "Technical",
    responseType: 'text',
    placeholder: "Please describe the process",
  },
  {
    id: "q123",
    text: "Does the entity generate RCM (RISK CONTROL MATRIX) Transactions?",
    subject: "Technical",
    responseType: 'yesno',
    options: [
      { value: "1", label: "Yes" },
      { value: "0", label: "No" },
    ],
  },
  {
    id: "q124",
    text: "Number of Users involved in AP Invoice Management",
    subject: "Technical",
    responseType: 'number',
    placeholder: "Enter number",
    validation: { required: true, min: 1 },
  },
  {
    id: "q125",
    text: "Number of Users involved in AR Invoice Management",
    subject: "Technical",
    responseType: 'number',
    placeholder: "Enter number",
    validation: { required: true, min: 1 },
  },
  {
    id: "q126",
    text: "Which ERP are you currently using? Name and Version.",
    subject: "Technical",
    responseType: 'text',
    placeholder: "Please provide ERP name and version",
  },
  {
    id: "q127",
    text: "Current Storage of Invoice Data",
    subject: "Technical",
    responseType: 'select',
    options: [
      { value: "database", label: "Database" },
      { value: "file_system", label: "File System" },
      { value: "cloud_storage", label: "Cloud Storage" },
      { value: "hybrid", label: "Hybrid" },
    ],
  },
  {
    id: "q128",
    text: "Do you require our team to perform end-to-end integration with your ERP? Or do you have your own team/vendor to perform integration?",
    subject: "Technical",
    responseType: 'select',
    options: [
      { value: "rsm_team", label: "RSM team to perform integration" },
      { value: "own_team", label: "Own team/vendor to perform integration" },
      { value: "both", label: "Both" },
    ],
  },
  {
    id: "q129",
    text: "Do you want AP invoice auto-integration with your ERP or just display on the Flick dashboard for manual data entry?",
    subject: "Technical",
    responseType: 'select',
    options: [
      { value: "auto_integration", label: "Auto-integration with ERP" },
      { value: "manual_entry", label: "Display on dashboard for manual entry" },
    ],
  },
  {
    id: "q130",
    text: "Do you have any other country that needs eInvoicing requirement apart from UAE?",
    subject: "Technical",
    responseType: 'yesno',
    options: [
      { value: "1", label: "Yes" },
      { value: "0", label: "No" },
    ],
  },
  {
    id: "q131",
    text: "Do you raise B2B/B2G Invoices via any POS/E-Commerce? If Yes, Mention their Names",
    subject: "Technical",
    responseType: 'text',
    placeholder: "Please list POS/E-Commerce systems or enter 'No'",
  },
  {
    id: "q132",
    text: "If Above Question is Yes, whether they will be able to be integrated with Rest APIs.",
    subject: "Technical",
    responseType: 'yesno',
    options: [
      { value: "1", label: "Yes" },
      { value: "0", label: "No" },
    ],
  },
  {
    id: "q133",
    text: "Is there any Vendor/ERP Provider who can integrate the eCommerce / POS Devices with eInvoicing Flick's APIs",
    subject: "Technical",
    responseType: 'text',
    placeholder: "Please provide vendor/ERP provider details or enter 'No'",
  },
  {
    id: "q134",
    text: "Do you have the current process related to Sales, Procurement mapped?",
    subject: "Technical",
    responseType: 'yesno',
    options: [
      { value: "1", label: "Yes" },
      { value: "0", label: "No" },
    ],
  },
  {
    id: "q135",
    text: "Are you following any compliance Standard.",
    subject: "Technical",
    responseType: 'text',
    placeholder: "Please list compliance standards or enter 'None'",
  },
  {
    id: "q136",
    text: "Additional Comments or Requirements",
    subject: "Technical",
    responseType: 'text',
    placeholder: "Please provide any additional comments or requirements",
  },
];
